export const mockData = [
    {
      key: 1,
      date: '2024-08-01',
      category: 'Alimentación',
      description: 'Compra en supermercado',
      amount: 50.25,
      payment_method: 'TARJETA',
      location: 'New York',
      notes: 'Compra de la semana',
      username: 'sanbmg@gmail.com',
    },
    {
      key: 2,
      date: '2024-08-02',
      category: 'Transporte',
      description: 'Gasolina para el coche',
      amount: 40.00,
      payment_method: 'EFECTIVO',
      location: 'Los Angeles',
      notes: '',
      username: 'montivero.marcio@gmail.com',
    },
    {
      key: 3,
      date: '2024-08-03',
      category: 'Ocio',
      description: 'Cena en restaurante',
      amount: 75.00,
      payment_method: 'TARJETA',
      location: 'Miami',
      notes: 'Cena con amigos',
      username: 'sanbmg@gmail.com',
    },
    {
      key: 4,
      date: '2024-08-04',
      category: 'Salud',
      description: 'Consulta médica',
      amount: 100.00,
      payment_method: 'TRANSFERENCIA',
      location: 'Chicago',
      notes: 'Chequeo anual',
      username: 'montivero.marcio@gmail.com',
    },
    {
      key: 5,
      date: '2024-08-05',
      category: 'Alimentación',
      description: 'Compra de frutas y verduras',
      amount: 30.50,
      payment_method: 'EFECTIVO',
      location: 'San Francisco',
      notes: '',
      username: 'sanbmg@gmail.com',
    },
    {
      key: 6,
      date: '2024-08-06',
      category: 'Transporte',
      description: 'Billete de tren',
      amount: 25.00,
      payment_method: 'TARJETA',
      location: 'Boston',
      notes: '',
      username: 'montivero.marcio@gmail.com',
    },
    {
      key: 7,
      date: '2024-08-07',
      category: 'Ocio',
      description: 'Entrada al cine',
      amount: 15.00,
      payment_method: 'EFECTIVO',
      location: 'New York',
      notes: 'Película: Inception',
      username: 'sanbmg@gmail.com',
    },
    {
      key: 8,
      date: '2024-08-08',
      category: 'Salud',
      description: 'Compra de medicamentos',
      amount: 20.00,
      payment_method: 'TARJETA',
      location: 'Los Angeles',
      notes: '',
      username: 'montivero.marcio@gmail.com',
    },
    {
      key: 9,
      date: '2024-08-09',
      category: 'Alimentación',
      description: 'Desayuno en cafetería',
      amount: 12.00,
      payment_method: 'TARJETA',
      location: 'San Diego',
      notes: 'Café y croissant',
      username: 'sanbmg@gmail.com',
    },
    {
      key: 10,
      date: '2024-08-10',
      category: 'Transporte',
      description: 'Taxi',
      amount: 18.00,
      payment_method: 'EFECTIVO',
      location: 'Las Vegas',
      notes: 'Desde el aeropuerto',
      username: 'montivero.marcio@gmail.com',
    },
    {
      key: 11,
      date: '2024-08-11',
      category: 'Ocio',
      description: 'Suscripción a Netflix',
      amount: 15.99,
      payment_method: 'TRANSFERENCIA',
      location: 'Seattle',
      notes: '',
      username: 'sanbmg@gmail.com',
    },
    {
      key: 12,
      date: '2024-08-12',
      category: 'Salud',
      description: 'Consulta dental',
      amount: 200.00,
      payment_method: 'TARJETA',
      location: 'Miami',
      notes: '',
      username: 'montivero.marcio@gmail.com',
    },
    {
      key: 13,
      date: '2024-08-13',
      category: 'Alimentación',
      description: 'Comida rápida',
      amount: 8.50,
      payment_method: 'EFECTIVO',
      location: 'Chicago',
      notes: '',
      username: 'sanbmg@gmail.com',
    },
    {
      key: 14,
      date: '2024-08-14',
      category: 'Transporte',
      description: 'Billete de avión',
      amount: 300.00,
      payment_method: 'TRANSFERENCIA',
      location: 'New York',
      notes: 'Viaje a San Francisco',
      username: 'montivero.marcio@gmail.com',
    },
    {
      key: 15,
      date: '2024-08-15',
      category: 'Ocio',
      description: 'Compra de videojuegos',
      amount: 60.00,
      payment_method: 'TARJETA',
      location: 'Houston',
      notes: '',
      username: 'sanbmg@gmail.com',
    },
    {
      key: 16,
      date: '2024-08-16',
      category: 'Salud',
      description: 'Examen de sangre',
      amount: 80.00,
      payment_method: 'EFECTIVO',
      location: 'Philadelphia',
      notes: '',
      username: 'montivero.marcio@gmail.com',
    },
    {
      key: 17,
      date: '2024-08-17',
      category: 'Alimentación',
      description: 'Compra en panadería',
      amount: 5.75,
      payment_method: 'TARJETA',
      location: 'San Francisco',
      notes: '',
      username: 'sanbmg@gmail.com',
    },
    {
      key: 18,
      date: '2024-08-18',
      category: 'Transporte',
      description: 'Alquiler de coche',
      amount: 120.00,
      payment_method: 'TARJETA',
      location: 'Orlando',
      notes: 'Alquiler por 2 días',
      username: 'montivero.marcio@gmail.com',
    },
    {
      key: 19,
      date: '2024-08-19',
      category: 'Ocio',
      description: 'Concierto de rock',
      amount: 90.00,
      payment_method: 'TRANSFERENCIA',
      location: 'Las Vegas',
      notes: '',
      username: 'sanbmg@gmail.com',
    },
    {
      key: 20,
      date: '2024-08-20',
      category: 'Salud',
      description: 'Sesión de fisioterapia',
      amount: 65.00,
      payment_method: 'EFECTIVO',
      location: 'Los Angeles',
      notes: '',
      username: 'montivero.marcio@gmail.com',
    },
  ];
  